import { describe, it, expect } from 'vitest';
import { mkdtemp, writeFile, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { extractPackagesUnderReview, createFileReader } from '../src/extract.js';
import type { FileReader } from '../src/extract.js';

/**
 * Build a synthetic FileReader from in-memory maps. Convenient for exercising
 * extraction logic without writing fixtures to disk.
 */
function memoryReader(opts: {
  head: Record<string, string>;
  base?: Record<string, string>;
  /** Map of directory paths to child dir names. Use 'apps' or '.' as keys. */
  headDirs?: Record<string, string[]>;
  baseDirs?: Record<string, string[]>;
}): FileReader {
  return {
    async readHead(p) {
      return p in opts.head ? opts.head[p]! : null;
    },
    async readAtRef(_ref, p) {
      if (!opts.base) return null;
      return p in opts.base ? opts.base[p]! : null;
    },
    async listHeadDir(p) {
      if (!opts.headDirs) return null;
      return p in opts.headDirs ? opts.headDirs[p]! : null;
    },
    async listAtRefDir(_ref, p) {
      if (!opts.baseDirs) return null;
      return p in opts.baseDirs ? opts.baseDirs[p]! : null;
    },
  };
}

describe('extract — workspace member-manifest warnings', () => {
  it('pnpm: missing member manifest warns and skips', async () => {
    const lockfile = [
      `lockfileVersion: '9.0'`,
      '',
      'importers:',
      '',
      '  .:',
      '    dependencies:',
      '      lodash.kebabcase:',
      '        specifier: 4.1.1',
      '        version: 4.1.1',
      '',
      '  apps/a:',
      '    dependencies:',
      '      is-number:',
      '        specifier: 6.0.0',
      '        version: 6.0.0',
      '',
      'packages:',
      '',
      '  is-number@6.0.0:',
      '    resolution: {integrity: sha512-xx}',
      '',
      '  lodash.kebabcase@4.1.1:',
      '    resolution: {integrity: sha512-yy}',
      '',
      'snapshots:',
      '  is-number@6.0.0: {}',
      '  lodash.kebabcase@4.1.1: {}',
      '',
    ].join('\n');
    const reader = memoryReader({
      head: {
        'pnpm-lock.yaml': lockfile,
        'package.json': '{"name":"root","version":"1.0.0","dependencies":{"lodash.kebabcase":"4.1.1"}}',
        // apps/a/package.json is intentionally absent
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    expect(r.warnings.some((w) => /apps\/a\/package\.json missing at HEAD/.test(w.message))).toBe(true);
  });

  it('npm: missing member manifest warns and skips', async () => {
    const lockfile = JSON.stringify({
      name: 'root',
      version: '1.0.0',
      lockfileVersion: 3,
      packages: {
        '': { name: 'root', version: '1.0.0', dependencies: { 'lodash.kebabcase': '4.1.1' } },
        'apps/a': { name: '@ws/a', version: '1.0.0', dependencies: { 'is-number': '6.0.0' } },
        'node_modules/lodash.kebabcase': { version: '4.1.1', integrity: 'sha512-xx' },
        'node_modules/is-number': { version: '6.0.0', integrity: 'sha512-yy' },
      },
    });
    const reader = memoryReader({
      head: {
        'package-lock.json': lockfile,
        'package.json': '{"name":"root","version":"1.0.0","workspaces":["apps/*"]}',
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    expect(r.warnings.some((w) => /apps\/a\/package\.json missing at HEAD/.test(w.message))).toBe(true);
  });
});

describe('extract — yarn workspaces field shapes', () => {
  it('object form ({ packages: [...] }) is recognised', async () => {
    // Drive only the workspaces-field extraction by providing yarn berry lockfile +
    // a manifest using the object form. We verify by checking that no glob
    // expansion occurs (no listDir is called) when packages array is empty.
    const reader = memoryReader({
      head: {
        'yarn.lock': '# This file is generated by running "yarn install" inside your project.\n\n__metadata:\n  version: 8\n\n',
        'package.json': '{"name":"root","version":"1.0.0","workspaces":{"packages":[]}}',
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    // An empty workspaces array means no members — extraction collapses to
    // the root-only path and emits no warnings.
    expect(r.warnings).toEqual([]);
  });

  it('malformed manifest does not throw — discovery returns empty list', async () => {
    const reader = memoryReader({
      head: {
        'yarn.lock': '# This file is generated by running "yarn install" inside your project.\n\n__metadata:\n  version: 8\n\n',
        'package.json': 'not valid json',
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    // A malformed root manifest causes the snyk parser to fail; we should see
    // a parse warning and an empty set.
    expect(r.warnings.length).toBeGreaterThan(0);
    expect(r.setUnderReview).toEqual([]);
  });
});

describe('extract — glob expansion edges', () => {
  it('literal pattern without `*` is used as-is; `**` patterns are skipped silently', async () => {
    // Build a yarn-v1 in-memory fixture where the root manifest lists both a
    // literal workspace path and an unsupported `**` glob. The literal path
    // should be honoured (manifest read, dep included); the `**` glob should
    // be silently ignored (no warning).
    const yarnLock = [
      '# THIS IS AN AUTOGENERATED FILE',
      '# yarn lockfile v1',
      '',
      'is-number@6.0.0:',
      '  version "6.0.0"',
      '  resolved "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz"',
      '  integrity sha512-xx',
      '',
    ].join('\n');
    const reader = memoryReader({
      head: {
        'yarn.lock': yarnLock,
        'package.json': '{"name":"root","version":"1.0.0","private":true,"workspaces":["packages/a","unsupported/**"]}',
        'packages/a/package.json': '{"name":"@ws/a","version":"1.0.0","dependencies":{"is-number":"6.0.0"}}',
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    // No warning about the `**` pattern — we silently skip it.
    expect(r.warnings.filter((w) => /missing/.test(w.message)).map((w) => w.message)).toEqual([]);
    // The is-number dep should be picked up via the literal packages/a path.
    expect(r.setUnderReview.map((p) => p.name)).toContain('is-number');
  });

  it('segment-internal wildcard (`pkg-*`) is matched against directory listing', async () => {
    const yarnLock = [
      '# THIS IS AN AUTOGENERATED FILE',
      '# yarn lockfile v1',
      '',
      'is-number@6.0.0:',
      '  version "6.0.0"',
      '  resolved "https://registry.yarnpkg.com/is-number/-/is-number-6.0.0.tgz"',
      '  integrity sha512-xx',
      '',
    ].join('\n');
    const reader = memoryReader({
      head: {
        'yarn.lock': yarnLock,
        'package.json': '{"name":"root","version":"1.0.0","private":true,"workspaces":["pkg-*"]}',
        'pkg-a/package.json': '{"name":"@ws/pkg-a","version":"1.0.0","dependencies":{"is-number":"6.0.0"}}',
      },
      headDirs: {
        '.': ['pkg-a', 'node_modules', 'src'],
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    expect(r.setUnderReview.map((p) => p.name)).toContain('is-number');
  });

  it('directory listing returning null leaves the glob unexpanded', async () => {
    // listHeadDir returns null when the parent dir doesn't exist; expandSimpleGlobs
    // should silently skip the unresolvable glob, leaving the member list empty.
    const yarnLock = [
      '# THIS IS AN AUTOGENERATED FILE',
      '# yarn lockfile v1',
      '',
    ].join('\n');
    const reader = memoryReader({
      head: {
        'yarn.lock': yarnLock,
        'package.json': '{"name":"root","version":"1.0.0","private":true,"workspaces":["nonexistent/*"]}',
      },
      // headDirs intentionally absent — listHeadDir returns null
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    // No crash, no member warnings (the glob simply expanded to nothing).
    expect(r.warnings.filter((w) => /missing/.test(w.message)).map((w) => w.message)).toEqual([]);
  });
});

describe('extract — yarn v2 workspace edge cases', () => {
  it('member with no manifest at HEAD emits the workspace-member warning', async () => {
    // Yarn v2 (berry) workspace with one declared but absent member.
    const yarnLock = [
      '# This file is generated by running "yarn install" inside your project.',
      '',
      '__metadata:',
      '  version: 8',
      '',
    ].join('\n');
    const reader = memoryReader({
      head: {
        'yarn.lock': yarnLock,
        'package.json': '{"name":"root","version":"1.0.0","private":true,"workspaces":["apps/*"],"packageManager":"yarn@4.0.0"}',
        // apps/a/package.json absent
      },
      headDirs: {
        '.': ['apps'],
        'apps': ['a'],
      },
    });
    const r = await extractPackagesUnderReview({ mode: 'scan', baseRef: null, reader });
    expect(r.warnings.some((w) => /apps\/a\/package\.json missing at HEAD/.test(w.message))).toBe(true);
  });
});

describe('createFileReader — directory listing', () => {
  it('listHeadDir returns directories only; ENOENT → null', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'lq-'));
    try {
      await mkdir(join(dir, 'sub-a'));
      await mkdir(join(dir, 'sub-b'));
      await writeFile(join(dir, 'a-file.txt'), '');
      const fs = await import('node:fs/promises');
      const reader = createFileReader({
        cwd: dir,
        fs: {
          readFile: (p, e) => fs.readFile(p, e),
          readdir: (p, o) => fs.readdir(p, o),
        },
        exec: async () => ({ stdout: '', stderr: '', code: 0 }),
      });
      const entries = await reader.listHeadDir('.');
      expect(entries?.sort()).toEqual(['sub-a', 'sub-b']);
      expect(await reader.listHeadDir('missing')).toBeNull();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('listAtRefDir parses git ls-tree output, strips path prefix, returns null on absent path', async () => {
    const reader = createFileReader({
      cwd: '/x',
      fs: {
        readFile: async () => '',
        readdir: async () => [],
      },
      exec: async (cmd, args) => {
        expect(cmd).toBe('git');
        expect(args).toEqual(['ls-tree', '-d', '--name-only', 'main:apps/']);
        return { stdout: 'apps/a\napps/b\n', stderr: '', code: 0 };
      },
    });
    expect(await reader.listAtRefDir('main', 'apps')).toEqual(['a', 'b']);
  });

  it('listAtRefDir returns null when git reports missing path', async () => {
    const reader = createFileReader({
      cwd: '/x',
      fs: {
        readFile: async () => '',
        readdir: async () => [],
      },
      exec: async () => ({
        stdout: '',
        stderr: "fatal: not a tree object 'main:nope/'",
        code: 128,
      }),
    });
    expect(await reader.listAtRefDir('main', 'nope')).toBeNull();
  });

  it('listAtRefDir throws when ref is unresolvable', async () => {
    const reader = createFileReader({
      cwd: '/x',
      fs: {
        readFile: async () => '',
        readdir: async () => [],
      },
      exec: async () => ({
        stdout: '',
        stderr: "fatal: bad revision 'nope'",
        code: 128,
      }),
    });
    await expect(reader.listAtRefDir('nope', 'apps')).rejects.toThrow(/bad revision/);
  });

  it('listAtRefDir omits trailing slash when listing tree root', async () => {
    const reader = createFileReader({
      cwd: '/x',
      fs: {
        readFile: async () => '',
        readdir: async () => [],
      },
      exec: async (_cmd, args) => {
        expect(args).toEqual(['ls-tree', '-d', '--name-only', 'main:']);
        return { stdout: 'apps\nsrc\n', stderr: '', code: 0 };
      },
    });
    expect(await reader.listAtRefDir('main', '.')).toEqual(['apps', 'src']);
  });
});
